import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Sessions',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'sessions'}
      ],
    },
    {
      type: 'category',
      label: 'Player Characters',
      items: [
        {type: 'autogenerated', dirName: 'player-characters'}
      ],
    },
    {
      type: 'category',
      label: 'Organizations',
      items: [
        {type: 'autogenerated', dirName: 'organizations'}
      ],
    },
    {
      type: 'category',
      label: 'Notable NPCs',
      items: [
        {type: 'autogenerated', dirName: 'npcs'}
      ],
    },
    {
      type: 'category',
      label: 'Locations',
      items: [
        {type: 'autogenerated', dirName: 'locations'}
      ],
    },
  ],
};

export default sidebars;
