import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// Function to get all session items sorted by date (newest first)
function getSessionsSortedByDate() {
  const sessionsDir = path.join(__dirname, 'docs', 'sessions');
  
  try {
    const files = fs.readdirSync(sessionsDir);
    const sessionData: Array<{id: string, date: Date, title: string}> = [];
    
    files.forEach(file => {
      if (file.endsWith('.md')) {
        const filePath = path.join(sessionsDir, file);
        const content = fs.readFileSync(filePath, 'utf8');
        const { data } = matter(content);
        
        if (data.date && data.title) {
          const docId = `sessions/${file.replace('.md', '')}`;
          sessionData.push({
            id: docId,
            date: new Date(data.date),
            title: data.title
          });
        }
      }
    });
    
    // Sort by date descending (newest first)
    sessionData.sort((a, b) => b.date.getTime() - a.date.getTime());
    
    // Return as sidebar items
    return sessionData.map(item => item.id);
    
  } catch (error) {
    console.error('Error reading session dates:', error);
    return [];
  }
}

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Transcripts',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: 'transcripts'}
      ],
    },
    {
      type: 'category',
      label: 'Player Characters',
      items: [
        {type: 'autogenerated', dirName: 'player-characters'}
      ],
    },
    {
      type: 'category',
      label: 'Organizations',
      items: [
        {type: 'autogenerated', dirName: 'organizations'}
      ],
    },
    {
      type: 'category',
      label: 'Notable NPCs',
      items: [
        {type: 'autogenerated', dirName: 'npcs'}
      ],
    },
    {
      type: 'category',
      label: 'Locations',
      items: [
        {type: 'autogenerated', dirName: 'locations'}
      ],
    },
    {
      type: 'category',
      label: 'Sessions',
      collapsed: false,
      items: getSessionsSortedByDate(),
    },
  ],
};

export default sidebars;
