// Types for data/session-stats.json (generated by scripts/extract_session_stats.py)

export interface SpeakerStats {
  name: string;
  canonical: string;
  role: 'dm' | 'pc' | 'guest';
  player: string | null;
  blocks: number;
  words: number;
  talk_seconds_est: number | null;
  word_share: number;
}

export type PersonalityAxis =
  | 'chaos'
  | 'heroism'
  | 'comedy'
  | 'immersion'
  | 'strategy'
  | 'curiosity';

export type PersonalityScores = Partial<Record<PersonalityAxis, number>>;

export interface SessionSuperlative {
  player: string | null;
  quote: string;
}

export interface SessionPersonality {
  scores: Record<string, PersonalityScores>;
  evidence: Record<string, Partial<Record<PersonalityAxis, string>>>;
  superlatives: {
    mvp?: SessionSuperlative;
    best_joke?: SessionSuperlative;
    most_chaotic?: SessionSuperlative;
    decision_driver?: string;
  };
}

export interface SessionRecord {
  id: string;
  type: 'session' | 'interlude';
  number: number;
  title: string;
  date: string;
  href: string;
  has_transcript: boolean;
  transcript_format: 'json' | 'md' | null;
  timing_quality: 'exact' | 'approx' | 'none';
  duration_seconds: number | null;
  block_count: number | null;
  word_count: number | null;
  speakers: SpeakerStats[];
  players_present: string[] | null;
  attendance_source: 'transcript' | 'recap' | 'none';
  mentions: {
    npcs: Record<string, number>;
    locations: Record<string, number>;
    pcs: Record<string, number>;
  };
  fun: {
    nat20_mentions: number;
    nat1_mentions: number;
  };
  personality: SessionPersonality | null;
}

export interface SpeakerTotals {
  name: string;
  canonical: string;
  role: 'dm' | 'pc' | 'guest';
  player: string | null;
  sessions: number;
  blocks: number;
  words: number;
  talk_seconds_est: number;
}

export interface PlayerPersonalityAggregate {
  sessions_scored: number;
  mean_scores: PersonalityScores;
  signature_evidence: Partial<
    Record<PersonalityAxis, { quote: string; session: string; score: number }>
  >;
  superlative_counts: {
    mvp: number;
    best_joke: number;
    most_chaotic: number;
    decision_driver: number;
  };
}

export interface Aggregate {
  total_sessions: number;
  sessions_with_transcripts: number;
  total_words: number;
  total_blocks: number;
  total_duration_seconds: number;
  speaker_totals: SpeakerTotals[];
  top_npcs: Record<string, number>;
  top_locations: Record<string, number>;
  top_pcs_mentioned: Record<string, number>;
  nat20_mentions: number;
  nat1_mentions: number;
  personality_by_player: Record<string, PlayerPersonalityAggregate>;
}

export interface SessionStatsData {
  schema_version: string;
  generated_by: string;
  sessions: SessionRecord[];
  aggregate: Aggregate;
}

// Slim per-session slice (data/session-stat-blocks.json) consumed by the
// recap-page stat blocks, so doc pages don't bundle the full dataset.
export interface StatBlockSpeaker {
  name: string;
  role: 'dm' | 'pc' | 'guest';
  word_share: number;
}

export interface StatBlockRecord {
  timing_quality: 'exact' | 'approx' | 'none';
  duration_seconds: number | null;
  word_count: number | null;
  players_present: string[] | null;
  attendance_source: 'transcript' | 'recap' | 'none';
  speakers: StatBlockSpeaker[];
  top_npcs: Record<string, number>;
  fun: {nat20_mentions: number; nat1_mentions: number};
  superlatives: {
    mvp?: SessionSuperlative;
    best_joke?: SessionSuperlative;
    most_chaotic?: SessionSuperlative;
  } | null;
}

export interface StatBlocksData {
  schema_version: string;
  generated_by: string;
  blocks: Record<string, StatBlockRecord>;
}
